### PR TITLE
feat: Add kubectl and oc to toolbox

### PR DESCRIPTION
**Pull request by mimotej**
## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

… Explain your changes.

## Description
SSIA
Resolves https://github.com/operate-first/toolbox/issues/53

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
/lgtm

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Comment by HumairAK** [comment]
can you also update this list: https://github.com/operate-first/toolbox#tools-included

**Comment by mimotej** [comment]
> can you also update this list: https://github.com/operate-first/toolbox#tools-included
@HumairAK I've added Kubeval, kubectl and oc to list thanks for reminder :+1:

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve
/unhold

**Pull request merged**
