### PR TITLE
Bump version to 0.3.1

### PR DESCRIPTION
**Pull request by HumairAK**

### CODE REVIEW

**Comment by HumairAK** [comment]
Let's wait for the tag-release-build to push it [here](https://quay.io/repository/operate-first/opf-toolbox?tab=tags) before merging

**Comment by HumairAK** [comment]
Forgot to add #11 -- changed to 0.3.1

**Comment by HumairAK** [comment]
Build found [here](https://quay.io/repository/operate-first/opf-toolbox?tab=tags) ready for merge.

**Review by 4n4nd — APPROVED** [review]
/lgtm

**Pull request merged**
