### PR TITLE
Update tooling to reflect the versions as they exist in opf cd repo

### LINKED ISSUE #6: Update helmsecrets/ksops/sops
These are not in sync with what our argocd instances is currently uses and we need to update these to the following: 
KSOPs: 2.3.3
SOPS: 3.6.1
Helm-Secrets: 3.4.1

We also want to switch to using the [new repo](url) for helm-secrets since the old one is deprecated.

### LINKED ISSUE #7: Move image to operate-first repo

### PR DESCRIPTION
**Pull request by HumairAK**
Fixes #7 
Fixes #6 

And update docs accordingly.

### CODE REVIEW

**Review by anishasthana — APPROVED** [review]
Changes lgtm

**Comment by HumairAK** [comment]
A  side effect of this pr is that ci builds will work properly (no ratelimiting issues)

**Review by tumido — APPROVED** [review]

**Comment by anishasthana** [comment]
We don't have an owners file in this repo. I wonder if that's why it's failing?

**Comment by HumairAK** [comment]
Not sure, gonna manual merge for now.

**Pull request merged**
